var files_dup =
[
    [ "action.c", "action_8c_source.html", null ],
    [ "action.h", "action_8h_source.html", null ],
    [ "buffer.c", "buffer_8c_source.html", null ],
    [ "buffer.h", "buffer_8h_source.html", null ],
    [ "client.c", "client_8c_source.html", null ],
    [ "client.h", "client_8h_source.html", null ],
    [ "cmdlib.c", "cmdlib_8c_source.html", null ],
    [ "cmdlib.h", "cmdlib_8h_source.html", null ],
    [ "CmdLine.h", "_cmd_line_8h_source.html", null ],
    [ "GlPainter.cpp", "_gl_painter_8cpp_source.html", null ],
    [ "GlPainter.h", "_gl_painter_8h_source.html", null ],
    [ "GlWindow.cpp", "_gl_window_8cpp_source.html", null ],
    [ "GlWindow.h", "_gl_window_8h_source.html", null ],
    [ "painter.c", "painter_8c_source.html", null ],
    [ "RCWindow.cpp", "_r_c_window_8cpp_source.html", null ],
    [ "RCWindow.h", "_r_c_window_8h_source.html", null ],
    [ "receiver.c", "receiver_8c_source.html", null ],
    [ "SDWindow.cpp", "_s_d_window_8cpp_source.html", null ],
    [ "SDWindow.h", "_s_d_window_8h_source.html", null ],
    [ "sender.c", "sender_8c_source.html", null ],
    [ "server.c", "server_8c_source.html", null ],
    [ "server.h", "server_8h_source.html", null ],
    [ "shared.h", "shared_8h_source.html", null ],
    [ "softgpio.c", "softgpio_8c_source.html", null ],
    [ "softgpio.h", "softgpio_8h_source.html", null ],
    [ "threads.c", "threads_8c_source.html", null ],
    [ "threads.h", "threads_8h_source.html", null ]
];